### ISSUE TITLE
No animation (collapsing) on focus and Cancel button not coming up

### ISSUE THREAD

**Issue by vivekverma007** [react-native-vietnam/react-native-search-box#82]
## Expected Behaviour
On focus Input field a collapse animation trigger and cancel button appears

## Happening
No animation trigger
No text alignment change

### react-native": "0.62.0"

![Screenshot_2020-04-10-11-32-27-652_com appx](https://user-images.githubusercontent.com/54973249/78967294-afb07080-7b1f-11ea-9079-89372361e10c.png)

**Comment by Ankit-96** [comment]
Same Issue, on focusing Input Field, cancel button does not come up
React Native: 0.62

**Comment by vivekverma007** [comment]
Hellow sir @Ankit-96 i have seen your fork of this project observation shown that you are 3 commits ahead ,is you resolved the issue regarding this topic if yes please give a reply.

**Comment by Ankit-96** [comment]
Hi Vivek,
Regarding the library, I have forked and did solve the problem. So
basically forwardRef is no more being used in RN 0.62 for which the cancel
button animation was not showing up.

Regards,

Ankit Raj
7064503339

**Comment by vivekverma007** [comment]
Thankyou @Ankit-96  for your reply,
I experienced this problem on applying this library into my project for many days and finally this going to complete my project from your updated code for `RN 0.62` and i hope many other people who are facing this problem using this `RN -v +`  will get helped from your contribution.
